import * as mongodb from "mongodb";
 //Our employees should have a name, position, and level.
 //https://www.mongodb.com/languages/mean-stack-tutorial
 //employee management web application -  MongoDB Atlas cluster.	
 //The _id field is optional because it's generated by MongoDB. 
 //Create an employee interface on the server side
//Applications built with the MEAN stack follow the client-server architecture. 
export interface Employee {
   name: string;
   position: string;
   level: "junior" | "mid" | "senior";
   _id?: mongodb.ObjectId;
}